# Decomposing a square matrix into eigenvectors and eigenvalues



In [1]:
import numpy as np

In [2]:
rng = np.random.default_rng()

## Create random eigenvectors

We'll start with a random 3x3 matrix, **X**, and compute its qr factorization, where q is orthonormal and r is upper-triangular. We'll use Q for our eigenvectors.

In [3]:
X = np.random.normal(size=(3,3))
print(X)

[[-0.68673821  1.63697258  0.1670926 ]
 [-0.70893234 -0.92882861  0.35372811]
 [ 0.09394488  1.66740759  0.24218231]]


In [4]:
Q, R = np.linalg.qr(X)
print(Q)

[[-0.6926439   0.56954586 -0.44256292]
 [-0.7150289  -0.46158967  0.52504156]
 [ 0.09475277  0.68011212  0.72695902]]


### Q should be invertable, but let's make sure

In [5]:
np.linalg.det(Q)

1.0000000000000002

In [6]:
np.linalg.inv(Q)

array([[-0.6926439 , -0.7150289 ,  0.09475277],
       [ 0.56954586, -0.46158967,  0.68011212],
       [-0.44256292,  0.52504156,  0.72695902]])

$ \mathbf{Q}\mathbf{Q}^{-1} = \mathbf{I}$

In [7]:
Q @ np.linalg.inv(Q)

array([[ 1.00000000e+00,  7.03180501e-17, -1.47357678e-16],
       [-2.51704873e-17,  1.00000000e+00,  1.19005188e-17],
       [ 1.06261237e-16, -3.57143360e-17,  1.00000000e+00]])

## Create eigenvalues

Let's create a vector of eigenvalues in decreasing order: [a, a/2, a/3] = [6/11, 3/11, 2/11]. 

In [8]:
eigen_vals = np.array([6/11, 3/11, 2/11])

## Compose A

$ \mathbf{A}=\mathbf{Q}\mathbf{\Lambda}\mathbf{Q}^{-1} $

In [9]:
A = Q @ np.diag(eigen_vals) @ np.linalg.inv(Q)
print(A)

[[ 0.38576407  0.15619501  0.01134867]
 [ 0.15619501  0.38710276 -0.05317606]
 [ 0.01134867 -0.05317606  0.22713317]]


## Now do the decomposition

Let's get back our eigenstuff.

In [10]:
eigen_vals, eigen_vectors = np.linalg.eig(A)

Annoyingly, it's not sorted, so let's sort it.

In [11]:
iis = np.flip(np.argsort(eigen_vals))
eigen_vals = eigen_vals[iis]
eigen_vectors = eigen_vectors[:,iis]

print(eigen_vals)
print(eigen_vectors)

[0.54545455 0.27272727 0.18181818]
[[-0.6926439  -0.56954586 -0.44256292]
 [-0.7150289   0.46158967  0.52504156]
 [ 0.09475277 -0.68011212  0.72695902]]
